### ISSUE TITLE
Directlinks from open-telekom-cloud.com not working

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/docsportal#79] opened 2023-02-09 19:41 UTC
At the bottom of every Core Services Site of the Homepage, there is a direct link to the corresponding docs page. But **none** of them are working right now! For example https://docs.otc.t-systems.com/en-us/as/index.html

The meant link is at the bottom of those sites for example on this page https://open-telekom-cloud.com/de/produkte-services/core-services/auto-scaling under "Weitere Informationen zu diesem Produkt" -> "Dokumentationen"

**Comment by markusobi0** [comment] 2023-02-09 19:44
on the english version of the homepage its also not working

**Comment by tischrei** [comment] 2023-02-15 09:34
We checked it and confirmed the issue. My colleague @Nils-Magnus try to get in touch with the colleagues hosting the public Open Telekom Cloud homepage.

**Comment by vladimirhasko** [comment] 2023-02-15 23:07
the issue is fixed now for all services. the default links are working now

**Closed by vladimirhasko** 2023-02-15 23:07 UTC
Labels: bug
