### ISSUE TITLE
Broken URI

### ISSUE THREAD

**Issue by pvbouwel** [opentelekomcloud-docs/docsportal#197] opened 2024-08-07 12:54 UTC
On page https://www.open-telekom-cloud.com/en/products-services/core-services/image-management-service
There is a link to https://docs.otc.t-systems.com/compute.html but that results in a 404

It seems that it should instead point to https://docs.otc.t-systems.com/computing.html

**Comment by tischrei** [comment] 2024-08-12 09:43
Hi @pvbouwel , thanks for highlighting the issue, but I was not able to find the link. Could you create a screenshot and paste it here?

**Comment by SebastianGode** [comment] 2024-09-04 07:43
@tischrei The issue is here:
![grafik](https://github.com/user-attachments/assets/557a63f0-c646-41c3-8001-a9c10a524d89)
It's the link for "[User Guide and API description](https://docs.otc.t-systems.com/compute.html)"

**Comment by vladimirhasko** [comment] 2024-09-04 13:56
fixed now

**Closed by vladimirhasko** 2024-09-04 13:56 UTC
Labels: question
